name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches: 
    - master
  workflow_dispatch:

jobs:
  build:
    name: Test on Node ${{ matrix.node_version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node_version: ['14']
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: npm install and build
      run: |
        npm install
        npm run build
